import type { FamousSolve } from "./famous.ts";

/** The solves, newest record first. Made once from the published sources named in each entry; `test/famous.test.ts` plays every one. */
export const FAMOUS_SOLVE_DATA: readonly FamousSolve[] = [
  {
    id: "zajder-2.76",
    size: 3,
    timeMs: 2760,
    solver: "Teodor Zajder",
    country: "Poland",
    competition: "GLS Big Cubes Gdańsk 2026",
    competitionId: "GLSBigCubesGdansk2026",
    from: "2026-02-07",
    to: "2026-02-08",
    record: "world record",
    scramble: "L B R2 B' R2 U2 F D R2 U R2 F2 D2 R U B L2",
    solution: "x'\nr' U F U' r U' r' U2 r' U r\nR U2' R2' U' R U R U2' R'\nU' F' r U R' U' r' F R",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "geng-3.05",
    size: 3,
    timeMs: 3050,
    solver: "Xuanyi Geng",
    country: "China",
    competition: "Shenyang Spring 2025",
    competitionId: "ShenyangSpring2025",
    from: "2025-04-13",
    to: "2025-04-13",
    record: "world record",
    scramble: "R2 D2 R2 D2 U' F2 D L2 B2 R' D R B2 U2 L R2 D U2 F R2",
    solution: "x2\nl2 F L' U' R\nU R' U2' R\nU L U' L'\nU L' U' L\nR U2' R' U' R U R'\nF R' F' r U R U' r' U",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "wang-3.08",
    size: 3,
    timeMs: 3080,
    solver: "Yiheng Wang",
    country: "China",
    competition: "XMUM Cube Open 2025",
    competitionId: "XMUMCubeOpen2025",
    from: "2025-02-15",
    to: "2025-02-16",
    record: "world record",
    scramble: "U2 R' D2 R B2 D2 B2 R2 B F U F R2 B2 R F' L2 F2 L",
    solution: "z' y\nU' D' r R' D U' R' U' D\nR U R'\nL U L' U' L U L2'\nU' L\nU2 R' U R U' R' U R\nU' R' U R' U' R3 U' R' U R U R' U' U R' U'",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "park-3.13",
    size: 3,
    timeMs: 3130,
    solver: "Max Park",
    country: "United States",
    competition: "Pride in Long Beach 2023",
    competitionId: "PrideinLongBeach2023",
    from: "2023-06-11",
    to: "2023-06-11",
    record: "world record",
    scramble: "D R' U2 F2 D U' B2 R2 L' F U' B2 U2 F L F' D'",
    solution: "x2\nR' D2 R' D L' U L D R' U' R D\nL U' L'\nU' R U R' y' U R' U' R\nRw' U' R U' R' U2 Rw U",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "du-3.47",
    size: 3,
    timeMs: 3470,
    solver: "Yusheng Du",
    country: "China",
    competition: "Wuhu Open 2018",
    competitionId: "WuhuOpen2018",
    from: "2018-11-24",
    to: "2018-11-25",
    record: "world record",
    scramble: "F U2 L2 B2 F' U L2 U R2 D2 L' B L2 B' R2 U2",
    solution: "y x'\nU R2 U' F' L F' U' L'\nU' R U R'\nR' U R U2' R' U R\nU R' U' R U' R' U2 R\nU",
    source: "http://cubesolv.es/solve/5757",
    checked: "2026-09-30",
  },
  {
    id: "zemdegs-4.22",
    size: 3,
    timeMs: 4220,
    solver: "Feliks Zemdegs",
    country: "Australia",
    competition: "Cube for Cambodia 2018",
    competitionId: "CubeforCambodia2018",
    from: "2018-05-06",
    to: "2018-05-06",
    record: "world record",
    scramble: "R2 L' F2 D2 F' D L2 B' D L U B2 U B2 D2 L2 D' F2 D",
    solution: "F' R' D' R\ny R U' R' u'\nU' R U R'\ny' L' U2 L U' L' U L\nd (U R' U' R)2\nU' R U2' R2' F R F' R U2' R'",
    source: "http://cubesolv.es/solve/5273",
    checked: "2026-09-30",
  },
  {
    id: "zemdegs-4.59",
    size: 3,
    timeMs: 4590,
    solver: "Feliks Zemdegs",
    country: "Australia",
    competition: "Hobart Summer 2018",
    competitionId: "HobartSummer2018",
    from: "2018-01-27",
    to: "2018-01-27",
    record: "world record",
    scramble: "B2 U L2 U R2 D2 B2 L2 R2 F' U' L2 R F' U L' B D F2 L",
    solution: "z2 y\nL U F' R' u\nR' U R\nL' U L U R U' R' U' R U R'\nU y' U R U' R' U' L' U' L\nU' R U' R' U R U' R'\nU R' U' F' U F R\nU2",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "cho-4.59",
    size: 3,
    timeMs: 4590,
    solver: "SeungBeom Cho",
    country: "Republic of Korea",
    competition: "ChicaGhosts 2017",
    competitionId: "Chicago2017",
    from: "2017-10-28",
    to: "2017-10-28",
    record: "world record",
    scramble: "U2 L' D2 L D2 R F2 D2 R' D2 U2 B U L U L' R D L2 F2 U2 R'",
    solution: "x2\nD' R' L2' U' F U' F' (D' U') U' R'\ny' R' U' R\ny' R U' R' U' R U R'\nU' R' U' F' U F R\nU'",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "ponce-4.69",
    size: 3,
    timeMs: 4690,
    solver: "Patrick Ponce",
    country: "United States",
    competition: "Rally In The Valley 2017",
    competitionId: "RallyInTheValley2017",
    from: "2017-09-02",
    to: "2017-09-02",
    record: "world record",
    scramble: "B2 R2 U F2 D2 B U' R U' L F L F' L2 R D R'",
    solution: "x' y2\nr' U D' R' F' U D'\nR' U R2\nU' R' U2 L' U L\nU' R U' R' U L U L'\nU U' U' F' (R U R' U') R' F R\nU' (R U R' U R U2' R')\nU2",
    source: "https://www.speedsolving.com/wiki/index.php?title=History_of_World_Records/3x3x3",
    checked: "2026-09-30",
  },
  {
    id: "akkersdijk-7.08",
    size: 3,
    timeMs: 7080,
    solver: "Erik Akkersdijk",
    country: "Netherlands",
    competition: "Czech Open 2008",
    competitionId: "CzechOpen2008",
    from: "2008-07-12",
    to: "2008-07-13",
    record: "world record",
    scramble: "D' R2 D L2 B2 L2 D' R2 F' L2 R' F D F' D' L' U2 F' R",
    solution: "y' x U' R2 x' U R' u\nU' R U' R'\nU' y' R U2 R' U' R U R'\nL' U L2 U' L'\nU L' U2 L U' L' U L U'\nU' F R U R' U' R U R' U' F' U2",
    reconstructedBy: "Lucas Garron",
    source: "http://archive.garron.us/solves/2008/erik_7_08.htm",
    checked: "2026-09-30",
  },
  {
    id: "nakajima-8.72",
    size: 3,
    timeMs: 8720,
    solver: "Yu Nakajima",
    country: "Japan",
    competition: "Kashiwa Open 2008",
    competitionId: "KashiwaOpen2008",
    from: "2008-05-05",
    to: "2008-05-05",
    record: "tied world record",
    scramble: "R' F' L' F U' D2 R D' L' U2 B2 D' F2 L' U' F' B2 L2",
    solution: "u' R' F l' L D2 x' u'\ny U' R U R' d' R' U' R\ny U' R' U' R U' R' U R\ny' U R U' R' U' L' U' L\nU' d' L' U L\nU y R2 U R U R' U' R' U' R' U R'",
    reconstructedBy: "Lucas Garron",
    source: "http://archive.garron.us/solves/2008/nakajima_8_72_final.htm",
    checked: "2026-09-30",
  },
  {
    id: "pons-11.75",
    size: 3,
    timeMs: 11750,
    solver: "Jean Pons",
    country: "France",
    competition: "Dutch Open 2005",
    competitionId: "DutchOpen2005",
    from: "2005-10-16",
    to: "2005-10-16",
    record: "world record",
    scramble: "D2 L D2 U2 F' U R2 B L R' B2 L F' L R D' U2",
    solution: "y2 r U x' U R' U R' z2 y' D2'\nU R' U' R2 U R'\nU' y' U' R U' R' U2 R U' R'\nU y R' U2 R U R' U' R\nU' y U' R' U R U' R' U' R\nU' R' U' R' F R F' U R\nR U R' U' R' F R2 U' R' U' R U R' F'",
    reconstructedBy: "Lucas Garron",
    source: "http://archive.garron.us/solves/2005/pons_11_75.htm",
    checked: "2026-09-30",
  },
];
